eu-digital-identity-wallet/eudi-srv-pid-issuer

- src/main/resources/templates/display-credentials-offer.html
- src/main/resources/templates/generate-credentials-offer-error.html
- src/main/resources/templates/generate-credentials-offer-form.html
> Use version agnostic webjar urls.

- .github/dependabot.yml
> Group and limit dependabot PRs.

- .github/workflows/ci.yml
- .github/workflows/publish-to-container-registry.yml
Replacing:
uses: gradle/gradle-build-action@v3
with
uses: gradle/actions/setup-gradle@v3
> Fix gradle-build-action

- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/IssueMobileDrivingLicence.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueMsoMdocPid.kt
> Fix mso_mdoc proof signing supported algs to EC

- docker-compose/haproxy/haproxy.conf
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/MetaDataApi.kt
> Expose SD-JWT VC Issuer metadata via `/.well-known/jwt-vc-issuer`.

- build.gradle.kts
- gradle/libs.versions.toml
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateCwtProof.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateJwtProof.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateProof.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/IssueMobileDrivingLicence.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueMsoMdocPid.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialConfiguration.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/JwtVcJsonProfile.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/MsoMdocProfile.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/SdJwtVcProfile.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/Types.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetCredentialIssuerMetaData.kt
- src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateJwtProofTest.kt
- src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateProofTest.kt
> Support CWT proofs

- gradle/libs.versions.toml
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/DefaultEncodeMobileDrivingLicenceInCbor.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/DefaultEncodePidInCbor.kt
This PR upgrades to v0.6.0 of `waltid-mdoc-credentials-jvm` library
> Upgrade to waltid-mdoc-credentials-jvm 0.6.0

- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetCredentialIssuerMetaData.kt
> Fully align SD-JWT-VC metadata

- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/EncodePidInSdJwtVc.kt
> Use the correct value for 'age_in_years' PID attribute.

- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/MetaDataApi.kt
> Fix SD-JWT-VC issuer metadata

- src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApi.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/EncryptResponseWithNimbus.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateProofs.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialRequest.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/MsoMdocProfile.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/SdJwtVcProfile.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetDeferredCredential.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt
- src/test/kotlin/eu/europa/ec/eudi/pidissuer/CredentialRequestTOTest.kt
- src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
- src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/EncryptCredentialResponseWithNimbusTest.kt
> Credential Endpoint/Deferred Credential Endpoint draft15 alignment

- README.md
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/EncodePidInSdJwtVc.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/status/GenerateStatusListTokenWithExternalService.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/Types.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/status/GenerateStatusListToken.kt
- src/main/resources/application.properties
> Support Status List Tokens in SD-JWT VC PIDs.

- docker-compose/haproxy/haproxy.conf
> Do not expose OpenID Connect Configuration under /.well-known/openid-configuration/idp/realms/pid-issuer-realm

- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/oauth/Claims.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/DefaultEncodePidInCbor.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/EncodePidInSdJwtVc.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/GetPidDataFromAuthServer.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/Pid.kt
- src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
> Update SD-JWT PID per ARF v1.8

- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/oauth/Claims.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/DefaultEncodePidInCbor.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/EncodePidInSdJwtVc.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/GetPidDataFromAuthServer.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/Pid.kt
- src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
Reverts eu-digital-identity-wallet/eudi-srv-pid-issuer#321
> Revert "Update SD-JWT PID per ARF v1.8"

- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/oauth/Claims.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/DefaultEncodePidInCbor.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/EncodePidInSdJwtVc.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/GetPidDataFromAuthServer.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/Pid.kt
- src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
> Align SD-JWT VC PID with ARF v1.8

- build.gradle.kts
> Replace Spring Dependency Management plugin with Spring Boot BOM.

- src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/IssuerUi.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApi.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/DPoPTokenReactiveAuthenticationManager.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/ServerDPoPAuthenticationTokenAuthenticationConverter.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/DefaultExtractJwkFromCredentialKey.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/EncryptResponseWithNimbus.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ExtractJwkFromCredentialKey.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ResolveDidUrl.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateJwtProof.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateProofs.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/X5c.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/EncodePidInSdJwtVc.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/qr/DefaultGenerateQrCode.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/status/GenerateStatusListTokenWithExternalService.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/util/EitherExtensions.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialRequest.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/CreateCredentialsOffer.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetDeferredCredential.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/jose/EncryptDeferredResponse.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/qr/GenerateQqCode.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/status/GenerateStatusListToken.kt
- src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/EncryptCredentialResponseWithNimbusTest.kt
- src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ResolveDidUrlTest.kt
> Remove usages of `Result<T>` and `runCatching`

- README.md
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
- src/main/resources/application.properties
> Add proxy settings for WebClient

- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/VerifyKeyAttestation.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/KeyAttestationJWT.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/OpenId4VciSpec.kt
- src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
> Rename key attestation JWT type to key-attestation+jwt

- src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApi.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/json/JsonSupport.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialIssuerMetaData.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetCredentialIssuerMetaData.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt
- src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
> Implement encrypted credential requests

- src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApi.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/DecryptRequestWithNimbus.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/EncryptResponseWithNimbus.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/persistence/InMemoryDeferredCredentialRepository.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/OpenId4VciSpec.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetDeferredCredential.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/IssueSpecificCredential.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/jose/EncryptDeferredResponse.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/persistence/LoadDeferredCredentialByTransactionId.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/persistence/StoreDeferredCredential.kt
- src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
> Deferred issuance request/response updates

- README.md
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/ehic/EncodeEuropeanHealthInsuranceCardInSdJwtVc.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/ehic/IssueSdJwtVcEuropeanHealthInsuranceCard.kt
> Remove `vctm` and `vct#integrity` from issued EHICs VCs

- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/DecryptRequestWithNimbus.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetDeferredCredential.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt
Improves error handling during Credential Request/Deferred Credential Request decryption.
Catches more errors.
> Improve error handling during Credential Request/Deferred Credential Request decryption

- src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApi.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetDeferredCredential.kt
- src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt
- src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
This PR:
1. Improves error descriptions reported to clients. 
2. Updates test cases to account for the improved error descriptions.
3. Fixes a test case that did not verify what it was supposed to test.
> Improve error descriptions
