eu-digital-identity-wallet/eudi-srv-pid-issuer

build.gradle.kts
After publication there is no good reason to have SNAPSHOT dependencies repository enabled.
Application can use stable releases of EUDIW libs.
This PR removes the snapshot repository from gradle
=> Remove snapshot repo from gradle

build.gradle.kts, gradle.properties, src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/CreateCredentialsOffer.kt, src/main/resources/application.properties
This PR
- Moves the version of the project to the `gradle.properties`
- Simplifies the URI of the credential offer 
For the 2nd point, until now application creates credential offers that look like
`eudi-openid4ci://credentialsOffer?credential_offer=...`
The PR simplifies this to
`eudi-openid4ci://?credential_offer=...`
=> Updated credential offer URI creation

README.md, docker-compose/docker-compose.yaml, src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt, src/main/resources/application-prod.properties, src/main/resources/application.properties, src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
1. Introduce a new property to configure the URL to be used to fetch the metadata of the authorization server. This is not necessarily derived from the public URL of the authorization server.
2. Enable parsing of X-Forwarded headers so that the server can successfully determine the currently accessed URI when behind a reverse proxy. When this is not enabled DPoP authentication does not work because `htu` differs from `ServerHttpRequest.uri`.
=> Authorization server metadata and DPoP fixes.

docker-compose/keycloak/realms/pid-issuer-realm-realm.json
Add the new redirect uri `eudi-issuance://authorization` for `eudiw` and `wallet-dev` clients in keycloak.
=> Register a new redirect uri for eudiw and wallet-dev clients.

docker-compose/keycloak/themes/pid-issuer/login/register.ftl
In newer Keycloak versions it's mandatory.
=> Add previously removed email attribute in registration form. 

gradle/libs.versions.toml
WaltId has updated their versioning scheme. They no longer provide 'frozen snapshots'. The old version of the mso jvm library is no longer available in their repository and as a result pid-issuer no longer build.
This updates the version of the waltid mso jvm library to the latest available version.
Reference: https://maven.waltid.dev/#/releases/id/walt/waltid-mdoc-credentials-jvm
=> Update waltid mso library to v0.3.1

src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueMsoMdocPid.kt
Enables proof of type CWT (in addition to JWT) for the PID in `mso_mdoc`
Closes #188
=> Enable CWT proofs for PID in mso_mdoc

.github/workflows/ci.yml, .github/workflows/publish-to-container-registry.yml
https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated
=> Update setup-gradle github action

src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialRequest.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt, src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
1. ~~RequestedResponseEncryption.Required now accepts JWK with keyUse null as well. When keyUse is null, the JWK can be used for all purposes, including encryption.~~
2. Properly verify during issuance that RequestedResponseEncryption is supported by the issuer's configured CredentialResponseEncryption. Previously when CredentialResponseEncryption was set to Required, but the CredentialRequestTO contained no CredentialResponseEncryptionTO, the issuance would continue and an unencrypted credential would be issued, even though the issuer was configured to require encryption.
Closes #204
=> Fix issues with Credential Response Encryption.

src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
An assertion in a test case in `WalletApiTest` was:
1. Incorrect
2. Not properly applied
This PR fixes the above issues.
=> Properly apply and fix incorrect assertion.

src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/EncryptResponseWithNimbus.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt, src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt, src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/EncryptCredentialResponseWithNimbusTest.kt
=> Remove c_nonce_expires_in

src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/IssuerSigningKey.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/EncodePidInSdJwtVc.kt
'x5c' must be included only when the configured Signing Key has a Certificate that contains the Issuer URL either as a SAN DNS name or SAN URI.
Closes #251
=> Conditionally Include the 'x5c' header claim in issued SD-JWT-VCs

build.gradle.kts, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/IssuerApi.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/IssuerUi.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApi.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/JWKExtensions.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateJwtProof.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateProofs.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/DefaultEncodeMobileDrivingLicenceInCbor.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/EncodeMobileDrivingLicenceInCbor.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/GetMobileDrivingLicenceData.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/GetMobileDrivingLicenceDataMock.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/IssueMobileDrivingLicence.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/EncodePidInSdJwtVc.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/GetPidData.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueMsoMdocPid.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialRequest.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/MsoMdocProfile.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/SdJwtVcProfile.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/CreateCredentialsOffer.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetDeferredCredential.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/IssueSpecificCredential.kt, src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateJwtProofTest.kt, src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateProofTest.kt, src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/GetMobileDrivingLicenceDataMockTest.kt
=> Removed deprecated context receivers

README.md, src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialIssuerMetaData.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetCredentialIssuerMetaData.kt
This PR adds new configuration properties for the Display objects of the Credential Issuer Metadata.
The following configuration properties:
```properties
issuer.metadata.display[0].name=Digital Credentials Issuer
issuer.metadata.display[0].locale=en
issuer.metadata.display[0].logo.uri=https://eudiw.dev/ic-logo.svg
issuer.metadata.display[0].logo.alternative-text=EU Digital Identity Wallet Logo
issuer.metadata.display[1].name=\u0395\u03ba\u03b4\u03cc\u03c4\u03b7\u03c2 \u03a8\u03b7\u03c6\u03b9\u03b1\u03ba\u03ce\u03bd \u0394\u03b9\u03b1\u03c0\u03b9\u03c3\u03c4\u03b5\u03c5\u03c4\u03b7\u03c1\u03af\u03c9\u03bd
issuer.metadata.display[1].locale=el
issuer.metadata.display[1].logo.uri=https://eudiw.dev/ic-logo.svg
issuer.metadata.display[1].logo.alternative-text=\u039b\u03bf\u03b3\u03cc\u03c4\u03c …
```
=> Make credential issuer display metadata configurable.

src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/MsoMdocProfile.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/SdJwtVcProfile.kt
As per draft15, SD-JWT VC and MSO MDoc Credential Requests no longer contain profile specific properties.
This PR removes `claims` from the related domain classes.
=> Remove `claims` from SD-JWT VC and MSO MDoc Credential Requests.

src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetCredentialIssuerMetaData.kt
=> Remove `credential_identifiers_supported` from Credential Issuer's Metadata.

src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueMsoMdocPid.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt
Add `trust_anchor` to MSO MDoc and SD-JWT VC PID metadata
Supersedes #307 which was closed due to Github not being able to process updates.
Closes #306
=> Add missing `trust_anchor` PID attribute in metadata.

src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/credential/DefaultResolveCredentialRequestByCredentialIdentifier.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/ehic/EncodeEuropeanHealthInsuranceCardInSdJwtVc.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/ehic/IssueSdJwtVcEuropeanHealthInsuranceCard.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialConfiguration.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialIssuerMetaData.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialRequest.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/JwtVcJsonProfile.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/MsoMdocProfile.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/SdJwtVcProfile.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/Types.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/credential/ResolveCredentialRequestByCredentialIdentifier.kt, src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
This PR adds support for issuing EHIC as an SD-JWT VC serialized using compact serialization.
Additionally, this PR augments the Specific Issuer matching mechanism to also consider any Credential Configuration Id that was provided in the Credential Request. If multiple Specific Issuers are matched, an error is raised and Issuance is cancelled.
=> Add support for issuing EHIC as SD-JWT VC Compact.

src/main/resources/vct/pid_arf18.json
=> Fix Json Schema for `nationalities`. The shared array can be empty.

build.gradle.kts, gradle/libs.versions.toml, src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/GetPidDataFromKeyCloak.kt, src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/qr/DefaultGenerateQrCode.kt
This PR drops the dependency on Keycloak Admin Client.
We only use a single API, that can be easily implemented using WebClient instead.
=> Drop Keycloak Admin Client

docker-compose/docker-compose.yaml, docker-compose/keycloak/realms/pid-issuer-realm-realm.json
This PR:
1. Updates Keycloak to v26.1.4-0
2. Enables `passkeys` feature
3. Updates `pid-issuer-realm` realm configuration to enable passkeys - *passkey registration is optional*
With the above:
* During new account creation, passkey registration is not required
* Passkey registration, both for new and existing accounts, can be done in Account Management -> Account Security -> Signing In (e.g. https://dev.authenticate.eudiw.dev/realms/pid-issuer-realm/account/account-security/signing-in). Here a user can register one or more passkeys
* During sign in, below the username/password form, a new button appears which when clicked, prompts the user to sign in using a registered passkey
> [!NOTE]
> https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt examples are not affected …
=> Enable passkeys support in Keycloak
